### ISSUE TITLE
Tag the current version?

### ISSUE THREAD

**Issue by crohr** [xeokit/xeokit-gltf-to-xkt#20]
Hello,

Thanks a lot for this project. Do you think you could tag the current version of the code so that we can use that when referencing the project? Currently we have to point to `master`, which could break things in the future. Also, publishing to NPM would be great (not sure what's missing?) :)

**Comment by Amoki** [comment]
There is an npm for this repo: https://www.npmjs.com/package/@xeokit/xeokit-gltf-to-xkt
But it's not really up to date.
+1 for git tag.
`npm version x.x.x` update the package.json, commit the update, and set a git tag in a single command!

**Comment by xeolabs** [comment]
Closing this because we've started tagging these past few releases.
