### ISSUE TITLE
Ability to use the converter from a node process instead of CLI has been removed

### ISSUE THREAD

**Issue by Amoki** [xeokit/xeokit-gltf-to-xkt#24]
The `package.json` defines a `main` to `src/index.js` which has been deleted.
This `index.js` was useful to invoke this module from a node script instead of the CLI.
```javascrip
const {glTFToXKT} = require('@xeokit/xeokit-gltf-to-xkt');

// do stuff
const xkt = glTFToXKT(gltf);
// do stuff with xkt binary
```

This avoid us to write the gltf on disk, write the xkt, and read it again to use it. Everything is done in memory.

New converters (`ConverterVX.js`) take paths as input and output so we must use disk.

This API has the advantage to easily handle gltf with attached files.

### Proposal 1
I think converters should take binary as input and return the xkt binary while `gltf2xkt.js` should be responsible to read and write data on disk.

```javascript
function convert(gltfBinary, attachments={}) {
	return xktBinary
}
```

Where `attachments` is an object `{fileName: binaryContent}` where `name` is the same name as defined the in gltf file.

We must know which files are needed before we open the gltf. The async loading would be easier to implement because they won't be optional and dynamic async loads.

The CLI with attached files is hard to implement with this solution.

### Proposal 2
Trade of between the current solution and proposal 1

```javascript
async function convert(gltfBinary, attachmentsDir) {
	return xktBinary
}
```

Where `attachmentsDir` is a path where we can find the attachents files. Files are dynamically loaded if needed. We don't need to know file names prior to gltf opening but attachment won't be in memory.

### Proposal 3
Mode complex but more flexible
```javascript
async function convert(gltfBinary, getAttachment) {
	return xktBinary
}
```

where getAttachment is a method to implement called each time we need to retrieve an attached file

```javascript
async function getAttachment(name) {
	// retrieve data from it's name
	return attachmentBinary
}
```

In the CLI use-case, getAttachments whould be a wrapper around `fs` to load local files.
In my use-case, it whould retrieve content from the Internet without write on disk.

What do you think?

I can implement the solution.

**Comment by xeolabs** [comment]
Proposal 3 looks good to me @Amoki, if you could implement it, that would be awesome.
