### ISSUE TITLE
CLI cant find gltf2xkt

### ISSUE THREAD

**Issue by EyeonimLuuk** [xeokit/xeokit-gltf-to-xkt#27]
Hello,

We’re having trouble executing the `gltf2xkt -v` command in CMD on a Windows server 2019 standard machine. We can execute the `gltf2xkt -v` command in a node CLI, as can be seen in the screenshots below. 
On this server we use `xeokit-gltf-to-xkt` version 0.0.4. We heard that @amoki may have some clues for us.
We would like to know what you think may be the cause of this issue.

**Regular CMD**
The command "gltf2xkt" is either misspelled or could not be found.
![Screenshot_204-2](https://user-images.githubusercontent.com/75077646/100353420-bf1cf500-2fee-11eb-92d4-51c6f6060c24.png)

**Node**
The command is executable in node CLI.
![Screenshot_205-2](https://user-images.githubusercontent.com/75077646/100353432-c7753000-2fee-11eb-8880-42a97aa40642.png)

**Regular CMD**
Executing in `xeokit-gltf-to-xkt` folder results in a Windows Script error. At row 1, char 1. Error: Invalid character. 
![Screenshot_206-2](https://user-images.githubusercontent.com/75077646/100353548-f5f30b00-2fee-11eb-8830-b8078cb231af.png)

Thank you in advance!

**Comment by Amoki** [comment]
The CLI config didn't change, I'd say it's a PATH problem.
Did you install the module with `npm -g` ?
Is the `npm -g` binaries install directory in your PATH ?

> Executing in xeokit-gltf-to-xkt folder results in a Windows Script error. At row 1, char 1. Error: Invalid character.

This is expected. You can't directly execute js files.
`C:\Users\Service_Meridian\xeokit-gltf-to-xkt> node gltf2xkt -v` should work. (It invokes node to execute the js file)

**Comment by Amoki** [comment]
https://stackoverflow.com/questions/10396305/npm-package-bin-script-for-windows

It's simpler on Unix because there is a way to tell the OS to execute the js script with node. There are no such way in Windows, so you must invoke `node`  with the script.
