### ISSUE TITLE
Wrong version number

### ISSUE THREAD

**Issue by wielinde** [xeokit/xeokit-gltf-to-xkt#28]
Hey friends,

apparently we have a version number issue (again). In version 0.0.3 the `gltf2xkt --version` reponds with 0.0.2. And in version 0.0.6 it responds with 0.0.4. Check this outdated line here https://github.com/xeokit/xeokit-gltf-to-xkt/blob/40e6610a6a40d54508325a9586b3e067298442f7/gltf2xkt.js#L10

I propose to have one single place of truth in the entire project and read that place everywhere else where needed. Otherwise we keep forgetting to update all places.

**Comment by xeolabs** [comment]
@wielinde thanks, now fixed in @xeokit/xeokit-gltf-to-xkt 0.0.61
