### ISSUE TITLE
Fix missing -m parameter

### ISSUE THREAD

**Issue by suryakumara** [xeokit/xeokit-gltf-to-xkt#37]
<img width="596" alt="Screen Shot 2021-05-18 at 2 37 34 PM" src="https://user-images.githubusercontent.com/51102773/118603664-c75c2d00-b7e6-11eb-8e42-9eecf25ad173.png">

Missing -m parameter

**Comment by Amoki** [comment]
You're converting to xkt v7, -m option exists from xkt v8.
Are you on the latest version?

**Comment by suryakumara** [comment]
@Amoki yes I used the latest version, from https://www.npmjs.com/package/@xeokit/xeokit-gltf-to-xkt/v/1.3.0 

and in the documentation there is no -m option either

**Comment by xeolabs** [comment]
My bad - didn't merge the branch before deploying - fixed in 1.3.1 - give it another shot
